FROM lscr.io/linuxserver/emulatorjs:latest

COPY index.js /emulatorjs/index.js
COPY profile.js /emulatorjs/profile.js
COPY public/index.html /emulatorjs/public/index.html
COPY public/css/index.css /emulatorjs/public/css/index.css
COPY public/js/index.js /emulatorjs/public/js/index.js
COPY frontend/index.html /emulatorjs/frontend/index.html
COPY frontend/filebrowser.html /emulatorjs/frontend/filebrowser.html
COPY frontend/css/index.css /emulatorjs/frontend/css/index.css
COPY frontend/css/filebrowser.css /emulatorjs/frontend/css/filebrowser.css
COPY frontend/js/index.js /emulatorjs/frontend/js/index.js
COPY frontend/js/filebrowser.js /emulatorjs/frontend/js/filebrowser.js
COPY nginx/site-confs/default /etc/nginx/site-confs/default
